app/documents/blueprint.py
# -*- coding: utf-8 -*-
import datetime

from flask import (
    Blueprint, render_template, request, redirect, url_for, flash,
    abort)
from flask_login import current_user, login_required
from sqlalchemy.sql.functions import current_timestamp

from app import db
from app.documents.forms import DocumentForm, DocumentModelForm
from app.models import Document, Source, slugify
from flask import current_app as app

documents = Blueprint('documents', __name__, template_folder='templates')


def save_db(o):
    try:
        db.session.add(o)
        db.session.commit()
    except Exception as e:
        return False
    return True


@documents.route('/')
@login_required
def index():
    q = request.args.get('q')

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    docs = Document.query.order_by(Document.id.asc())

    if q:
        docs = Document.query.filter(
            Document.title.contains(q) | Document.text.contains(q)
        )
    pages = docs.paginate(page=page, per_page=5)

    return render_template(
        'documents/index.html', pages=pages, documents_page=True)


@documents.route('/create/', methods=['POST', 'GET'])
@login_required
def create_document():
    form = DocumentForm(request.form)
    if request.method == 'POST' and form.validate():
        # TODO add validate to form
        title = form.title.data
        created = form.created.data
        text = form.text.data
        source_name = form.source_name.data
        source_url = form.source_url.data
        source = Source(name=source_name, url=source_url)
        save_db(source)

        document = Document(
            title=title, text=text, created=created, author=current_user,
            source=source
        )
        saved = save_db(document)
        if saved:
            return redirect(url_for('documents.index'))
        else:
            flash('Документ не был создан')

    return render_template(
        'documents/create.html', document_create_page=True, form=form
    )


@documents.route('/edit/<int:pk>', methods=['POST', 'GET'])
@login_required
def edit_document(pk):
    document = Document.query.filter_by(id=pk).first()
    time_edit_limit = document.created_at + datetime.timedelta(hours=1)

    if not current_user.has_role('admin'):
        if time_edit_limit <= datetime.datetime.now():
            flash('Time is up')
            return redirect(url_for('documents.index'))

    if request.method == 'POST':
        cnt = document.editor_count or 0
        cnt += 1
        document.editor_count = cnt
        document.updated_at = current_timestamp()
        db.session.add(document)
        db.session.commit()

        form = DocumentModelForm(formdata=request.form, obj=document)
        form.populate_obj(document)
        db.session.commit()
        return redirect(url_for('documents.index'))

    form = DocumentModelForm(obj=document)
    return render_template('documents/edit.html', document_edit_page=True,
                           document=document, form=form)


@documents.route('/generate_documents/',)
@login_required
def generate_documents():
    title = 'Document {}'
    text = render_template('documents/generate_text/text.html')
    created = current_timestamp()
    url = '{}{}'

    for i in range(1, app.config['GENERATE_COUNT_DOCUMENTS']):
        tmp_url = url.format(format(request.base_url), i)
        tmp_text = '{} {}'.format(text, i)
        source = Source(name='Source {}'.format(i), url=tmp_url)
        save_db(source)

        document = Document(
            title=title.format(i), text=tmp_text, created=created,
            author=current_user, source=source,
            url=slugify(title.format(i))
        )
        save_db(document)
    return redirect(url_for('documents.index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
	<a class="navbar-brand" href="/">Test task</a>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item {% if home_page %}active{% endif %}">
				<a class="nav-link" href="#">Home</a>
			</li>
			{% if current_user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link {% if documents_page %}active{% endif %}" href="{{ url_for('documents.index') }}">Documents</a>
				</li>
				<li class="nav-item">
					<a class="nav-link {% if document_create_page %}active{% endif %}" href="{{ url_for('documents.create_document') }}">Create document</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('documents.generate_documents') }}">Generate documents</a>
				</li>

			{% endif %}

		</ul>
		<form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		</form>
		<ul class="nav navbar-nav navbar-right">
			{% if current_user.is_authenticated %}
				<li><a class="nav-link" href="{{ url_for('logout') }}">Logout</a></li>
			{% else %}
				<li><a class="nav-link" href="{{ url_for('security.login') }}">Login</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<div class="text-info text-center">
					<h1>{% block content_title %}{% endblock %}</h1>
					{% with messages = get_flashed_messages() %}

						{% if messages %}
								<ul class='list-inline'>
									{% for message in messages %}
										<li>{{ message }}</li>
										<li>{{ message }}</li>
									{% endfor %}
								</ul>
						{% endif %}

					{% endwith %}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				{% block content %}{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content_title %}
	Test task
{% endblock %}

{% block content %}
	login please
{% endblock %}